//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaiMudra.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaiMudraEntities : DbContext
    {
        public SaiMudraEntities()
            : base("name=SaiMudraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAbout> tblAbouts { get; set; }
        public virtual DbSet<tblBlog> tblBlogs { get; set; }
        public virtual DbSet<tblContact> tblContacts { get; set; }
        public virtual DbSet<tblGallary> tblGallaries { get; set; }
        public virtual DbSet<tblKattarVadak> tblKattarVadaks { get; set; }
        public virtual DbSet<tblRegistration> tblRegistrations { get; set; }
    }
}
